%% This script is to aggregate the IEN data to five minutes, or other intervals
clear
clc
close all

%% Set the default parameters
params=struct(...
    'Interval', 5*60,...
    'StartDate', '2017-6-27',...
    'EndDate', '2017-8-23',...
    'Method', 'Interpolation',...
    'InputFolder', 'Default',...
    'OutputFolder','Default');

dp=aggregate_IEN_data_longer_interval(params);
dp.aggregation_by_default_interval;
