%% This script is to run the detector health report for the City of Arcadia
clear
clc
close all


%% Load the detector config file
config=load_config('arterial_system_detector_config.xlsx', 'Arcadia');


%% Extract health analysis report
params=struct(...
    'StartDate',        struct(...
        'Year',     2015,...
        'Month',    11,...
        'Day',      4),...
    'EndDate',        struct(...
        'Year',     2015,...
        'Month',    11,...
        'Day',      11),...
    'DetectorList', config);

extract_health_report(params);